using Microsoft.CodeAnalysis;
using OmniNet.SourceGenerators.Core;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

namespace OmniNet.SourceGenerators.Core.Tests;

public class MethodBuilderTests
{
    private static string GetGeneratedCode(SourceBuilder sb)
    {
        return sb.GetOutputForTesting();
    }

    private static string GetGeneratedMethod(Action<TypeBuilder> buildAction)
    {
        const string prefix = "// <auto-generated/>\r\n#nullable enable\r\n\r\npublic partial class TestClass\r\n{\r\n";
        const string suffix = "\r\n}\r\n";

        var sb = new SourceBuilder();
        var typeBuilder = sb.BuildClass("TestClass")
            .WithAccessibility(Accessibility.Public)
            .WithPartial()
            .Append()
            .AppendOpenType();

        buildAction(typeBuilder);

        typeBuilder.Dispose();

        var code = GetGeneratedCode(sb);
        if (code.StartsWith(prefix) && code.EndsWith(suffix))
        {
            code = code.Substring(prefix.Length, code.Length - prefix.Length - suffix.Length);
        }

        return code.UnifyCodeLineEndings();
    }

    [Test]
    public async Task SimpleVoidMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            type.BuildMethod("DoSomething")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .OpenBody()
                .AppendLine("// implementation")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public void DoSomething()
            	{
            		// implementation
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithReturnType_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference intType = "int";
            type.BuildMethod("GetValue", intType)
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .OpenBody()
                .AppendLine("return 42;")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public int GetValue()
            	{
            		return 42;
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task StaticMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference stringType = "string";
            type.BuildMethod("GetMessage", stringType)
                .WithAccessibility(Accessibility.Public)
                .WithStatic()
                .OpenParameters()
                .OpenBody()
                .AppendLine("return \"Hello\";")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public static string GetMessage()
            	{
            		return "Hello";
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task AsyncMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference taskType = "System.Threading.Tasks.Task";
            type.BuildMethod("DoWorkAsync", taskType)
                .WithAccessibility(Accessibility.Public)
                .WithAsync()
                .OpenParameters()
                .OpenBody()
                .AppendLine("await System.Threading.Tasks.Task.Delay(100);")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public async System.Threading.Tasks.Task DoWorkAsync()
            	{
            		await System.Threading.Tasks.Task.Delay(100);
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task PartialMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            type.BuildMethod("OnInitialize")
                .WithAccessibility(Accessibility.Private)
                .WithPartial()
                .OpenParameters()
                .AppendAbstract();
        });

        await Assert.That(code).IsEqualTo("""
            	private partial void OnInitialize();
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task VirtualMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            type.BuildMethod("DoSomething")
                .WithAccessibility(Accessibility.Public)
                .WithVirtual()
                .OpenParameters()
                .OpenBody()
                .AppendLine("// base implementation")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public virtual void DoSomething()
            	{
            		// base implementation
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task AbstractMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            type.BuildMethod("DoSomething")
                .WithAccessibility(Accessibility.Public)
                .WithAbstract()
                .OpenParameters()
                .AppendAbstract();
        });

        await Assert.That(code).IsEqualTo("""
            	public abstract void DoSomething();
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task OverrideMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference stringType = "string";
            type.BuildMethod("ToString", stringType)
                .WithAccessibility(Accessibility.Public)
                .WithOverride()
                .OpenParameters()
                .AppendExpression("\"TestClass\"");
        });

        await Assert.That(code).IsEqualTo("""
            	public override string ToString() => "TestClass";
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithNewModifier_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            type.BuildMethod("DoSomething")
                .WithAccessibility(Accessibility.Public)
                .WithNew()
                .OpenParameters()
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public new void DoSomething()
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithSingleParameter_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference stringType = "string";
            type.BuildMethod("SetName")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AddParameter(stringType, "name")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public void SetName(string name)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithMultipleParameters_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference stringType = "string";
            TypeReference intType = "int";
            type.BuildMethod("SetData")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AddParameter(stringType, "name")
                .AddParameter(intType, "age")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public void SetData(string name, int age)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithDefaultParameter_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference intType = "int";
            type.BuildMethod("Increment")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AddParameter(intType, "step", "1")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public void Increment(int step = 1)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithRefParameter_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference intType = "int";
            type.BuildMethod("Swap")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AddRefParameter(intType, "a")
                .AddRefParameter(intType, "b")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public void Swap(ref int a, ref int b)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithOutParameter_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference boolType = "bool";
            TypeReference intType = "int";
            type.BuildMethod("TryParse", boolType)
                .WithAccessibility(Accessibility.Public)
                .WithStatic()
                .OpenParameters()
                .AddParameter((TypeReference)"string", "input")
                .AddOutParameter(intType, "result")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public static bool TryParse(string input, out int result)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithInParameter_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference intType = "int";
            type.BuildMethod("Process")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AddInParameter(intType, "value")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public void Process(in int value)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MethodWithParamsParameter_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference intType = "int";
            type.BuildMethod("Sum", intType)
                .WithAccessibility(Accessibility.Public)
                .WithStatic()
                .OpenParameters()
                .AddParamsParameter(intType, "values")
                .OpenBody()
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	public static int Sum(params int[] values)
            	{
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ExpressionBodiedMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference intType = "int";
            type.BuildMethod("GetConstant", intType)
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AppendExpression("42");
        });

        await Assert.That(code).IsEqualTo("""
            	public int GetConstant() => 42;
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ExplicitInterfaceMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference interfaceType = "IDisposable";
            type.BuildMethod("Dispose")
                .WithExplicitInterfaceImplementation(interfaceType)
                .OpenParameters()
                .OpenBody()
                .AppendLine("// cleanup")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            	void IDisposable.Dispose()
            	{
            		// cleanup
            	}
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ExplicitStaticInterfaceMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedMethod(type =>
        {
            TypeReference interfaceType = "IFactory";
            TypeReference instanceType = "TestClass";
            type.BuildMethod("Create", instanceType)
                .WithExplicitInterfaceImplementation(interfaceType)
                .WithStatic()
                .OpenParameters()
                .AppendExpression("new TestClass()");
        });

        await Assert.That(code).IsEqualTo("""
            	static TestClass IFactory.Create() => new TestClass();
            """.UnifyCodeLineEndings());
    }
}