using Microsoft.CodeAnalysis;

namespace OmniNet.SourceGenerators.Core.Tests;

public class NestedTypeBuilderTests
{
    private static string GetGeneratedCode(Action<SourceBuilder> buildAction)
    {
        const string prefix = "// <auto-generated/>\r\n#nullable enable\r\n\r\n";
        const string suffix = "\r\n";

        var sb = new SourceBuilder();
        buildAction(sb);
        
        var code = sb.GetOutputForTesting();
        if (code.StartsWith(prefix) && code.EndsWith(suffix))
        {
            code = code.Substring(prefix.Length, code.Length - prefix.Length - suffix.Length);
        }

        return code.UnifyCodeLineEndings();
    }

    [Test]
    public async Task EmptyNestedClass_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Private)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	private class InnerClass
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedClassWithPublicAccessibility_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public class InnerClass
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedClassWithProtectedAccessibility_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Protected)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	protected class InnerClass
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedStruct_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedStruct("InnerStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public struct InnerStruct
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedInterface_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedInterface("IInnerInterface")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public interface IInnerInterface
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedRecord_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedRecord("InnerRecord")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public record InnerRecord
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedRecordStruct_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedRecordStruct("InnerRecordStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public record struct InnerRecordStruct
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedClassWithMembers_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference stringType = "string";
            innerType.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public class InnerClass
            	{
            		public string Name { get; set; }
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task MultipleNestedClasses_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            {
                using var innerType1 = outerType.BuildNestedClass("InnerClass1")
                    .WithAccessibility(Accessibility.Public)
                    .Append()
                    .AppendOpenType();
            }

            {
                using var innerType2 = outerType.BuildNestedClass("InnerClass2")
                    .WithAccessibility(Accessibility.Private)
                    .Append()
                    .AppendOpenType();
            }
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public class InnerClass1
            	{
            	}
            
            	private class InnerClass2
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task DeeplyNestedClasses_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var middleType = outerType.BuildNestedClass("MiddleClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = middleType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public class MiddleClass
            	{
            		public class InnerClass
            		{
            		}
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedClassWithPropertyAndOuterClassWithProperty_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference intType = "int";
            outerType.BuildProperty(intType, "OuterId")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference stringType = "string";
            innerType.BuildProperty(stringType, "InnerName")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public int OuterId { get; set; }
            
            	public class InnerClass
            	{
            		public string InnerName { get; set; }
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedPartialClass_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .WithPartial()
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .WithPartial()
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public partial class OuterClass
            {
            	public partial class InnerClass
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedClassInStruct_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildStruct("OuterStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public struct OuterStruct
            {
            	public class InnerClass
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedStructInStruct_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildStruct("OuterStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            using var innerType = outerType.BuildNestedStruct("InnerStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public struct OuterStruct
            {
            	public struct InnerStruct
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task NestedClassWithInheritance_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var outerType = sb.BuildClass("OuterClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference baseType = "BaseClass";
            TypeReference interfaceType = "IDisposable";
            using var innerType = outerType.BuildNestedClass("InnerClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendInheritance(baseType)
                .AppendInheritance(interfaceType)
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class OuterClass
            {
            	public class InnerClass : BaseClass, IDisposable
            	{
            	}
            }
            """.UnifyCodeLineEndings());
    }
}
