using Microsoft.CodeAnalysis;
using OmniNet.SourceGenerators.Core;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

namespace OmniNet.SourceGenerators.Core.Tests;

public class PropertyBuilderTests
{
    private static string GetGeneratedProperty(Action<TypeBuilder> buildAction)
    {
        const string prefix = "// <auto-generated/>\r\n#nullable enable\r\n\r\npublic partial class TestClass\r\n{\r\n";
        const string suffix = "\r\n}\r\n";

        var sb = new SourceBuilder();
        var typeBuilder = sb.BuildClass("TestClass")
            .WithAccessibility(Accessibility.Public)
            .WithPartial()
            .Append()
            .AppendOpenType();

        buildAction(typeBuilder);

        typeBuilder.Dispose();

        var code = sb.GetOutputForTesting();
        if (code.StartsWith(prefix) && code.EndsWith(suffix))
        {
            code = code.Substring(prefix.Length, code.Length - prefix.Length - suffix.Length);
        }

        return code.UnifyCodeLineEndings();
    }

    [Test]
    public async Task ImplicitGetterSetter_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(result).IsEqualTo("public string Name { get; set; }");
    }

    [Test]
    public async Task ImplicitGetterWithInitSetter_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter(initOnly: true)
                .Append();
        });

        await Assert.That(result).IsEqualTo("public string Name { get; init; }");
    }

    [Test]
    public async Task RequiredProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "Id")
                .WithAccessibility(Accessibility.Public)
                .WithRequired()
                .WithImplicitGetter()
                .WithImplicitSetter(initOnly: true)
                .Append();
        });

        await Assert.That(result).IsEqualTo("public required string Id { get; init; }");
    }

    [Test]
    public async Task PropertyWithInitializer_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference intType = "int";
            typeBuilder.BuildProperty(intType, "DefaultCounter")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .WithInitializer("10")
                .Append();
        });

        await Assert.That(result).IsEqualTo("public int DefaultCounter { get; set; } = 10;");
    }

    [Test]
    public async Task StaticPropertyWithExpressionGetter_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "StaticName")
                .WithAccessibility(Accessibility.Public)
                .WithStatic()
                .WithExplicitGetterExpression("\"StaticNameValue\"")
                .Append();
        });

        await Assert.That(result).IsEqualTo("""public static string StaticName => "StaticNameValue";""");
    }

    [Test]
    public async Task ExplicitInterfaceProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            TypeReference interfaceType = "IMyInterface";
            typeBuilder.BuildProperty(stringType, "Name")
                .WithExplicitInterfaceImplementation(interfaceType)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(result).IsEqualTo("string IMyInterface.Name { get; set; }");
    }

    [Test]
    public async Task ExplicitStaticInterfaceProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            TypeReference interfaceType = "IMyGenericInterface<MyClass>";
            typeBuilder.BuildProperty(stringType, "StaticProperty")
                .WithExplicitInterfaceImplementation(interfaceType)
                .WithStatic()
                .WithExplicitGetterExpression("\"StaticValue\"")
                .Append();
        });

        await Assert.That(result).IsEqualTo("""static string IMyGenericInterface<MyClass>.StaticProperty => "StaticValue";""");
    }

    [Test]
    public async Task VirtualProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "VirtualName")
                .WithAccessibility(Accessibility.Public)
                .WithVirtual()
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(result).IsEqualTo("public virtual string VirtualName { get; set; }");
    }

    [Test]
    public async Task AbstractProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "AbstractName")
                .WithAccessibility(Accessibility.Public)
                .WithAbstract()
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(result).IsEqualTo("public abstract string AbstractName { get; set; }");
    }

    [Test]
    public async Task OverrideProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "OverrideName")
                .WithAccessibility(Accessibility.Public)
                .WithOverride()
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(result).IsEqualTo("public override string OverrideName { get; set; }");
    }

    [Test]
    public async Task GetterOnlyProperty_GeneratesCorrectSyntax()
    {
        var result = GetGeneratedProperty(typeBuilder =>
        {
            TypeReference stringType = "string";
            typeBuilder.BuildProperty(stringType, "DefaultName")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithInitializer("\"DefaultValue\"")
                .Append();
        });

        await Assert.That(result).IsEqualTo("""public string DefaultName { get; } = "DefaultValue";""");
    }
}
