using Microsoft.CodeAnalysis;

namespace OmniNet.SourceGenerators.Core.Tests;

public class TypeBuilderTests
{
    private static string GetGeneratedCode(Action<SourceBuilder> buildAction)
    {
        const string prefix = "// <auto-generated/>\r\n#nullable enable\r\n\r\n";
        const string suffix = "\r\n";

        var sb = new SourceBuilder();
        buildAction(sb);
        
        var code = sb.GetOutputForTesting();
        if (code.StartsWith(prefix) && code.EndsWith(suffix))
        {
            code = code.Substring(prefix.Length, code.Length - prefix.Length - suffix.Length);
        }

        return code.UnifyCodeLineEndings();
    }

    [Test]
    public async Task EmptyClass_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task EmptyPartialClass_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .WithPartial()
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public partial class TestClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithSingleProperty_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference stringType = "string";
            type.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            	public string Name { get; set; }
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithMultipleProperties_SeparatesWithBlankLine()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference stringType = "string";
            TypeReference intType = "int";

            type.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();

            type.BuildProperty(intType, "Age")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            	public string Name { get; set; }
            
            	public int Age { get; set; }
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithSingleMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            type.BuildMethod("DoSomething")
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .OpenBody()
                .AppendLine("// implementation")
                .Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            	public void DoSomething()
            	{
            		// implementation
            	}
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithPropertyAndMethod_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference stringType = "string";
            type.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();

            type.BuildMethod("GetGreeting", stringType)
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AppendExpression("$\"Hello, {Name}\"");
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            	public string Name { get; set; }
            
            	public string GetGreeting() => $"Hello, {Name}";
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task EmptyInterface_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildInterface("ITestInterface")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public interface ITestInterface
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task EmptyStruct_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildStruct("TestStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public struct TestStruct
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task EmptyRecord_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildRecord("TestRecord")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public record TestRecord
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task EmptyRecordStruct_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildRecordStruct("TestRecordStruct")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public record struct TestRecordStruct
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task InternalClass_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("InternalClass")
                .WithAccessibility(Accessibility.Internal)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            internal class InternalClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task PrivateClass_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("PrivateClass")
                .WithAccessibility(Accessibility.Private)
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            private class PrivateClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithoutExplicitAccessibility_GeneratesWithoutAccessModifier()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("DefaultClass")
                .Append()
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            class DefaultClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithInheritance_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            TypeReference baseType = "BaseClass";
            using var type = sb.BuildClass("DerivedClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendInheritance(baseType)
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class DerivedClass : BaseClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithMultipleInterfaces_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            TypeReference interface1 = "IDisposable";
            TypeReference interface2 = "IComparable";
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendInheritance(interface1)
                .AppendInheritance(interface2)
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass : IDisposable, IComparable
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ClassWithBaseClassAndInterface_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            TypeReference baseClass = "BaseClass";
            TypeReference interfaceType = "IDisposable";
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendInheritance(baseClass)
                .AppendInheritance(interfaceType)
                .AppendOpenType();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass : BaseClass, IDisposable
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task DisposeClosure_ClosesTypeCorrectly()
    {
        var code = GetGeneratedCode(sb =>
        {
            var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            type.Dispose();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task TypeBuilderBuildProperty_WithITypeSymbol_GeneratesCorrectly()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference intType = "int";
            type.BuildProperty(intType, "Count")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            	public int Count { get; set; }
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task TypeBuilderBuildMethod_WithITypeSymbolReturnType_GeneratesCorrectly()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("TestClass")
                .WithAccessibility(Accessibility.Public)
                .Append()
                .AppendOpenType();

            TypeReference boolType = "bool";
            type.BuildMethod("IsValid", boolType)
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AppendExpression("true");
        });

        await Assert.That(code).IsEqualTo("""
            public class TestClass
            {
            	public bool IsValid() => true;
            }
            """.UnifyCodeLineEndings());
    }

    [Test]
    public async Task ComplexClassWithMultipleMembers_GeneratesCorrectSyntax()
    {
        var code = GetGeneratedCode(sb =>
        {
            using var type = sb.BuildClass("PersonService")
                .WithAccessibility(Accessibility.Public)
                .WithPartial()
                .Append()
                .AppendOpenType();

            TypeReference stringType = "string";
            TypeReference intType = "int";
            TypeReference boolType = "bool";

            type.BuildProperty(stringType, "Name")
                .WithAccessibility(Accessibility.Public)
                .WithRequired()
                .WithImplicitGetter()
                .WithImplicitSetter(initOnly: true)
                .Append();

            type.BuildProperty(intType, "Age")
                .WithAccessibility(Accessibility.Public)
                .WithImplicitGetter()
                .WithImplicitSetter()
                .Append();

            type.BuildMethod("IsAdult", boolType)
                .WithAccessibility(Accessibility.Public)
                .OpenParameters()
                .AppendExpression("Age >= 18");
        });

        await Assert.That(code).IsEqualTo("""
            public partial class PersonService
            {
            	public required string Name { get; init; }
            
            	public int Age { get; set; }
            
            	public bool IsAdult() => Age >= 18;
            }
            """.UnifyCodeLineEndings());
    }
}
